[{
	"id": 2,
	"name": "文章归档",
	"url": "/archives",
	"priority": 0,
	"target": "_self",
	"icon": "",
	"parentId": 0,
	"team": "主菜单",
	"children": []
}, {
	"id": 38,
	"name": "日志",
	"url": "/journals",
	"priority": 1,
	"target": "_self",
	"icon": "",
	"parentId": 0,
	"team": "主菜单",
	"children": []
}, {
	"id": 5,
	"name": "友情链接",
	"url": "/links",
	"priority": 2,
	"target": "_self",
	"icon": "",
	"parentId": 0,
	"team": "主菜单",
	"children": []
}, {
	"id": 4,
	"name": "关于页面",
	"url": "/s/about",
	"priority": 3,
	"target": "_self",
	"icon": "",
	"parentId": 0,
	"team": "主菜单",
	"children": []
}, {
	"id": 39,
	"name": "应用程序",
	"url": "https://app.luodachui.cn",
	"priority": 4,
	"target": "_blank",
	"icon": "",
	"parentId": 0,
	"team": "主菜单",
	"children": []
}]
